### PR TITLE
Package 1 12 themes

### LINKED ISSUE #282: Support 1.12 release script
jQuery UI 1.12 runs this during the release: https://github.com/jquery/jquery-ui/blob/9644e7bae9116edaf8d37c5b38cb32b892f10ff6/build/release.js#L37-L55

Testing with:
```
node release.js --pre-release=1.12.0-beta --remote=jzaefferer/jquery-ui
```
I eventually get this error:
```
/Users/jzaefferer/dev/jquery/jquery-release/__release/repo/node_modules/download.jqueryui.com/lib/jquery-ui-files.js:76
		if ( !minified[ file.path ] || options.skipCache ) {
		              ^
TypeError: Cannot read property 'ui/data.js' of undefined
    at Object.JqueryUiFiles.min (/Users/jzaefferer/dev/jquery/jquery-release/__release/repo/node_modules/download.jqueryui.com/lib/jquery-ui-files.js:76:17)
    at Builder_1_11_0.min (/Users/jzaefferer/dev/jquery/jquery-release/__release/repo/node_modules/download.jqueryui.com/lib/builder-1-11.js:99:17)
    at Array.map (native)
    at Array._.extend.map (/Users/jzaefferer/dev/jquery/jquery-release/__release/repo/node_modules/download.jqueryui.com/lib/files.js:24:37)
    at Builder_1_11_0 (/Users/jzaefferer/dev/jquery/jquery-release/__release/repo/node_modules/download.jqueryui.com/lib/builder-1-11.js:119:5)
    at Object.Builder.build (/Users/jzaefferer/dev/jquery/jquery-release/__release/repo/node_modules/download.jqueryui.com/lib/builder.js:59:31)
    at _build (/Users/jzaefferer/dev/jquery/jquery-release/__release/repo/node_modules/download.jqueryui.com/lib/themes-packer.js:53:12)
    at /Users/jzaefferer/dev/jquery/jquery-release/__release/repo/node_modules/download.jqueryui.com/node_modules/async/lib/async.js:486:21
    at /Users/jzaefferer/dev/jquery/jquery-release/__release/repo/node_modules/download.jqueryui.com/node_modules/async/lib/async.js:185:13
    at iterate (/Users/jzaefferer/dev/jquery/jquery-release/__release/repo/node_modules/download.jqueryui.com/node_modules/async/lib/async.js:108:13)
```
In builder.js, there's nothing specific to 1.12: https://github.com/jquery/download.jqueryui.com/blob/master/lib/builder.js#L58-L62

### PR DESCRIPTION
**Pull request by jzaefferer**
Fixes #282 

Goes together with https://github.com/jquery/jquery-ui/pull/1642/files

----

* [x] Missing license info in header comments.
* [x] Includes header comment is missing the individual effects.
* [x] AMD wrappers are not stripped from each module.
* [x] Minified CSS files don't have header comments for includes or edit URL.

### CODE REVIEW

**Comment by scottgonzalez** [comment]
Missing license info in header comments.

**Comment by scottgonzalez** [comment]
Includes header comment is missing the individual effects.

**Comment by scottgonzalez** [comment]
AMD wrappers are not stripped from each module.

**Comment by scottgonzalez** [comment]
Minified CSS files don't have header comments for includes or edit URL.

**Comment by rxaviers** [comment]
Worth checking if the same @scottgonzalez's comments also apply to the regular 1.12 package. If not, that package could be used as baseline for fixing this one.

**Comment by scottgonzalez** [comment]
Much better!

**Comment by jzaefferer** [comment]
Turned out 2 out of the 4 issues were invalid (looking at old files in `dist/`), fixed the other two. Merged and published as 2.1.2.

**Pull request merged**
