### PR TITLE
Fix ThemeRoller demo

### PR DESCRIPTION
**Pull request by jzaefferer**
This fixes a bunch of issues:

* [x] Update `template/themeroller/demo.html`, replace body selector with `#themeroller`
* [x] Broken dialog demo
* [x] Broken tooltip demo
* [x] Switching themes results in visual glitches on tabs and ruins ui-widget-shadow demo
* [x] Shadows look bad for non-Base gallery themes. The config made sense for the old ui-widget-content element, but not for how we use the class in 1.12
* [x] overlay background images don't work anymore. While base doesn't use one, other themes still do

Of the two commits, only the first should land in master, the other is for testing this locally. To do so:

* check out this PR, run `npm link`
* run `node server.js --console`
* go to your `jqueryui.com` repo
* run `npm link download.jqueryui.com`
* edit `Gruntfile.js` to use `host: "http://localhost:8088",`
* run `grunt deploy` and wait a while

### CODE REVIEW

**Comment by rxaviers** [comment]
It looks good. Thanks

**Comment by jzaefferer** [comment]
> Should this change be reflected in template/zip/index-1-12.html

Yeah, I'll make the same change there.

Any idea why other themes break the demo?

**Comment by jzaefferer** [comment]
Fixed the zip template. Will leave this for @rxaviers to look at the remaining issue. My instructions above might help to set this up.

**Comment by rxaviers** [comment]
@jzaefferer, 

> Switching themes results in visual glitches on tabs and ruins ui-widget-shadow demo

The theme switch itself causes no glitches on tabs for me. But, clicking the "Gallery" tab does. Shown below.

out

If you have a different issue, please just let me know.

**Comment by rxaviers** [comment]
The above issue is due to the 2-columns layout using floats.

**Comment by jzaefferer** [comment]
That's the issue I've seen. Apparently I misinterpreted the cause.

**Comment by rxaviers** [comment]
After fix
out

**Comment by rxaviers** [comment]
> Shadows look bad for non-Base gallery themes. The config made sense for the old ui-widget-content element, but not for how we use the class in 1.12

Do you believe TR is not updating the theme as it should, or do you believe the jQuery UI 1.12 theme updates don't look well for other themes?

**Comment by jzaefferer** [comment]
> Do you believe TR is not updating the theme as it should, or do you believe the jQuery UI 1.12 theme updates don't look well for other themes?

The problem seems to be the mix of new markup with old themes (or more specific, their parameters). The old themes use quite different offsets for the shadow, which looks bad with the new markup. They never looked good in the first place, so either we just continue ignoring this, or we update all existing themes to use sane shadow parameters. The latter might conflict when using older UI versions.

**Comment by rxaviers** [comment]
> overlay background images don't work anymore. While base doesn't use one, other themes still do

https://github.com/jquery/jquery-ui/commit/79c4fa1e7a09a3d28f0f8ff7a5b9f41a6d6e123d#diff-ff24a972bba1a2ecf79314fd9a5d048fL399

**Comment by rxaviers** [comment]
FWIW, if someone needs a simple code to test TR variable replacements: https://gist.github.com/rxaviers/c95e8ad5f7dfbd4ee188

**Comment by jzaefferer** [comment]
So we removed the variables for setting an overlay background image - but why did we do that? Why not just keep the variables, with no defaults?

**Comment by jzaefferer** [comment]
Replaced by #261, which is the same as this branch, but rebased, without the temp commits.

**Pull request closed without merging**
