### PR TITLE
Grunt: Extend build-packages task to support 1.12

### PR DESCRIPTION
**Pull request by jzaefferer**
To test locally, run `grunt prepare` once, then:
```
mkdir tmpresources
grunt build-packages:tmpresources
```
Unzip a few files and compare differences between 1.11 and 1.12. What I noticed so far and figured acceptable:
* 1.12 package adds AUTHORS.txt, LICENSE.txt and package.json compared to 1.11 package. We added those on purpose.
* 1.12 themes package contains sames files as non-themes package, along with the themes folder. Doesn't hurt.

If it fails to build 1.9.2 packages, just remove that version from `config.json` temporarily.

### CODE REVIEW

**Comment by scottgonzalez** [comment]
Looks good. It'd be nice if the themes zip didn't contain the JS, but I'm not too concerned about it.

**Comment by jzaefferer** [comment]
Excluding the JS files is easy enough. It would still include 4 css files in the root folder (jquery-ui.css, jquery-ui.min.css, jquery-ui.theme.css, jquery-ui.theme.min.css).

**Comment by scottgonzalez** [comment]
And that would be the new default theme. I think that's fine.

**Comment by jzaefferer** [comment]
Updated. Could you test once more? Then I'll merge and publish this and update jqueryui.com accordingly.

**Comment by scottgonzalez** [comment]
Looks good.

**Pull request merged**
