### PR TITLE
Config: Allow different jQuery UI version to be specified for ThemeRoller page

### PR DESCRIPTION
**Pull request by rxaviers**

### CODE REVIEW

**Comment by rxaviers** [comment]
@jzaefferer @scottgonzalez , this is what I have in mind.

**Comment by jzaefferer** [comment]
This still seems wrong. Can we revert the TR changes we made for 1.12 instead? Then revert-revert those once 1.12 is stable.

**Comment by rxaviers** [comment]
ThemeRoller is wrong [1] and the goal of this PR isn't to fix it.

Having said that, I do agree with you that your suggestion is definitely a better fix than the workaround provided here. The goal of this PR is to be the "minimal updates to get 1.12.0-beta.1 announced" in a timely manner. Although, if you want to pursue for your suggestion, I can help by providing guidances. Pretty much the commit history can be used to revert the TR changes.

1: ThemeRoller should be based on the selected version, not using a static one like it currently does. FWIW, Mobile's TR has a better architecture than this one.

**Comment by scottgonzalez** [comment]
@jzaefferer Are you ok with using this solution for now and implementing a real fix before 1.13?

**Comment by jzaefferer** [comment]
Yeah, it'll do. We had those changes live for a while now anyway.

**Pull request closed without merging**
